name: Deploy GraphQL Yoga example
on:
  push:
    branches:
      - main
    paths:
      - examples/graphql-yoga/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "fresh-graphql-yoga"
          entrypoint: "./examples/graphql-yoga/main.ts"
