name: Publish to JSR
on:
  push:
    branches:
      - main
    paths-ignore:
      - examples/**

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        # run: npx jsr publish
        run: |
          curl -fsSL https://deno.land/install.sh | sh
          export DENO_INSTALL="/home/runner/.deno"
          export PATH="$DENO_INSTALL/bin:$PATH"
          deno publish
