name: Publish to JSR
on:
  push:
    branches:
      - main
    paths-ignore:
      - examples/**

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1

      - name: Publish package
        # run: npx jsr publish
        run: deno publish
